apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config-sample
spec:
  groups:
    - name: example_settings
      title: Grafana Settings
      description: Please provide the following
      items:
        - name: default_settings
          title: Use Default Settings?
          help_text: Uncheck box to override default settings
          type: bool
          default: "1"
        - name: 
          title: enable_persistance
          help_text: This option will create a persistent volume
          type: text
          when: repl{{ ConfigOptionEquals "default_settings" "0" }}
